### ISSUE TITLE
How To Parse?

### ISSUE THREAD

**Issue by chigkim** [splendidtoad/pyrealpro#15]
Is there a way to reverse and parse from url string?
It would be awesome to be able to parse entire things like this one.
https://www.irealb.com/forums/showthread.php?12753-Jazz-1350-Standards

**Comment by tinpan-io** [comment]
Agreed, being able to parse songs and do stuff with them would be cool although I'm not sure if/when I'll get around to working on that. I'm closing this as a duplicate of #9
